### ISSUE TITLE
SciPipe doesn't fail on missing output files

### ISSUE THREAD

**Issue by samuell** [scipipe/scipipe#101]
It appeared through some of @jonalv's workflows, that scipipe does not properly fail when some declared outputs of a process are not properly created. These will AFAIK fail when trying to read from non-existing files in downstream processes, but it would be much more helpful when debugging to get the error where it happens.

**Comment by jonalv** [comment]
It would also be good if things could stay backwards compatible so I can easily fix my workflows which would break if this issue is fixed perhaps using a flag that allows for files to not be created...

**Comment by samuell** [comment]
Realizing that this is a duplicate of #54 , so closing and moving the discussion there.
