### ISSUE TITLE
Contributing to scipipe - working with github+golang

### ISSUE THREAD

**Issue by nyue** [scipipe/scipipe#113]
I have tried out scipipe and hope to contribute to it.

I am relatively new to golang and have a hard time testing out local changes I made in my test main program as it keeps pulling in the zip archive versioned copy of scipipe. Hence it is not picking my changes I made to the locally clone copy of scipipe.

I am familiar with the traditional way working with C++ and Python but Golang is quite challenging from a contribution perspective.

Any advice/workflow/pointer/best-practices ?

Cheers

**Comment by samuell** [comment]
Hi @nyue and thanks for trying out scipipe!

What is your current workflow for testing changes? Did you install scipipe via the `go get` command mainly?

I realize that the project is missing a contributors guide(!)

The workflow I have been using the most, is to go where scipipe is installed via `go get`, and replace the scipipe folder there with a git cloned version.

This might only work if you have set the GOROOT and GOPATH environment variables manually, and I think the Go project has been moving away from that, so this might not be the best way for the future. I have to check into that.

But to specify how I have been doing it:

- I have been installing Go by downloading the tarball into my home folder, and unpacking it into `~/go`.
- I have been putting my own Go projects in `~/proj/go`
- I have then been setting GOROOT and GOPATH as follows:
  ```
  GOROOT=~/go
  GOPATH=~/proj/go
  ```
- Then, when I do `go get github.com/scipipe/scipipe/...`, it ends up in `~/proj/go/src/github.com/scipipe/scipipe`
- I then have replaced this folder with the one I get by cloning the git repo into that very folder.
- After each change in the scipipe source, I think I typically need to run 
  ```
  go install github.com/scipipe/scipipe/...
  ```
  ... to have those changes build and installed into the build libraries in `~/go/proj/pkg` (if I recall correctly).
- Then, those changes should be available to my local workflow repos, wherever I store them.

So, the proper workflow for the future might or might not be some version of the above.

Hope this helps, until we have a proper contributors guide!

**Comment by nyue** [comment]
Regarding the contributors' guide, are you planning a separate document or are you thinking of an additional section in the current README.md file ?

**Comment by samuell** [comment]
That would probably be a separate .md page under the docs/ folder, which is what will end up on the documentation site at https://scipipe.org

**Comment by samuell** [comment]
Many thanks for contributing the [contributors page](https://scipipe.org/contributing/), @nyue ! Closing this issue for now. Please re-open if you think it is needed.
