### ISSUE TITLE
Serialized workflow description in JSON ?

### ISSUE THREAD

**Issue by nyue** [scipipe/scipipe#115]
Hi,

  I am looking into the possibility of using SciPipe for use outside of bioinformatics, namely film/visual-effects and possibly AEC.

  Most of my work experience lately is in the film/vfx industry so I am looking to hook up SciPipe to studio facility running what we call a farm with software like Tractor (from Pixar) and maybe Deadline (Thinkbox).

  I have also recently spent time at CSL (Pharmaceutical) setting up an HPC cluster running SLURM and integrating with CWL for the bioinformatics R&D.

  I would like to know if SciPipe has a serialise description of the FBP in a form like JSON with which I can write translator to generate industry specific job management files.

  In my short time running some of the demo code, I see *.audit.json files which are generated after a workflow has completed. I would like to generate the workflow description without running the workflow.

  I am looking for something like the Dot output but in a JSON format with enough detail for me to recreate all the necessarily detail to submit jobs to SLURM, Tractor, Deadline or generate CWL, WDL or other workflow files for submission via their respective runtime like Cromwell.

Cheers

**Comment by samuell** [comment]
Hi @nyue,

Interesting usecase!

So, is the idea to use SciPipe mainly for coding up the graph, and then using the generated graph as a configuration to a different system?

There is not currently such a serialization, although it should not be too hard to create one, in a similar way as the dot export is done now.

It is a little bit "unfortunate" that SciPipe ended up being very closely tied to file system based storage. I have been thinking a lot about how to break out the generic pipelining functionality into a generic library, a bit similar to [FlowBase](http://flowbase.org), but with smarter ports, making it possible to use for other tasks such as providing (dataflow-based) scheduling for other systems.

There are some ways to do that I think, but in general the lack of Generics in Go makes this a rather complicated task, probably involving a few workarounds, if we want to have typed ports and avoid a lot of manual code duplication.

Generics is on its way though, so I might get to this in time for its general availability, I hope. In the meantime, it seems SciPipe is a little limited to file system based scenarios.

Btw, for using SLURM, I guess you already saw the pointers given in [this wiki page](https://scipipe.org/howtos/hpc/)? (This is how we have been running some workloads on SLURM in our work).

**Comment by samuell** [comment]
@nyue Closing for now. Please re-open if you have any further input or questions!
