### ISSUE TITLE
Broken example link

### ISSUE THREAD

**Issue by apaleyes** [scipipe/scipipe#154]
Hi! Thanks for the package, it's quite impressive.

Wanted to report a broken link on this page: https://scipipe.org/howtos/parameters/ . Static parameters example was removed, yet the link still sits in the docs, probably worth updating the docs page.

Cheers!

**Comment by samuell** [comment]
Many thahks for reporting, @apaleyes ! Fixed now.

**Comment by apaleyes** [comment]
That was fast! But the broken link is still there. There were two of them:
* Under Static Parameters/See also section - still alive
* Under Relevant examples section - fixed now

**Comment by samuell** [comment]
Ouch, thanks! Fixed now (I hope :) )!

**Comment by apaleyes** [comment]
indeed, fully fixed now
