### ISSUE TITLE
Procs Without Outputs May Cause Deadlocks

### ISSUE THREAD

**Issue by dwmunster** [scipipe/scipipe#77]
## Expected Behavior
When creating a workflow with a component with no OutPorts/OutParamPorts, the workflow should execute successfully every time.

## Current Behavior
In a non-deterministic fashion, the workflow will intermittently deadlock.

## Possible Solution
If a Proc has no outputs, then [this](https://github.com/scipipe/scipipe/blob/9cc628/workflow.go#L379-L386) is triggered and the proc is removed from `wf.procs`. If this Proc is processed in the loop beginning on [line 342](https://github.com/scipipe/scipipe/blob/9cc628/workflow.go#L342) before its inputs, then the lookup on [Line 350](https://github.com/scipipe/scipipe/blob/9cc628/workflow.go#L350) fails and the ports are disconnected. Since this processes is still started, it will then deadlock waiting for input. The non-deterministic behavior is due to the non-deterministic iteration order over `wf.procs`.

## Steps to Reproduce
https://gist.github.com/dwmunster/ca74431417e49d1490f0576fc17cece6

## Possible Implementation
The lookup on [Line 350](https://github.com/scipipe/scipipe/blob/9cc628/workflow.go#L350) could check if the inport belongs to the driver process. Alternatively, another alternative is to perform a topological sort on the processes and process them in that order, thus guaranteeing that any driver process has its input processed first.

**Comment by samuell** [comment]
Many thanks for reporting, @dwmunster ! A fix for this is now pushed to the develop branch.

Still pondering a good way to add a test that triggers the error (when present). Ideas welcome.

**Comment by samuell** [comment]
> Still pondering a good way to add a test that triggers the error (when present). Ideas welcome.

OTOH, the whole test suite seems to complete much more robustly. I do have memories of random glitches before. Really glad you spotted this one.
